encoding: utf-8
excerpt_separator: '<!-- excerpt -->'
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge
  hard_wrap: false

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # disable: true
    # Rouge Options › https://github.com/jneen/rouge#full-options

    # css_class: 'highlight'
    # line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      start_line: 1
    block:
      line_numbers: true
      start_line: 1
